"""
Query Output Manager
=====================
Orchestrates SQL generation + YAML config writing for one table.

This is the single entry point used by the pipeline to:
  1. Build all validation SQL queries via SQLQueryGenerator
  2. Save YAML config file   → config/bronze/data_validation/<table>.yaml
  3. Save count YAML         → config/bronze/count_validation/bronze.yaml
  4. Return a GenerationResult with paths and summary

SQL files are NOT written to disk — queries live only inside the YAML files.

PK-Free Design
--------------
Primary key handling is deferred to a future milestone.
All queries are generated without PK-based ORDER BY, duplicate checks,
or missing-row checks. Column ordering follows the schema discovery order.

AI Model Tracking
-----------------
The model used for rule assignment is passed through and embedded in both
the SQL file header comment and the YAML config header.

Usage:
    from generated_queries import QueryOutputManager

    manager = QueryOutputManager()
    result = manager.generate(
        table_name="events",
        pg_schema="public",
        pg_table="events",
        sf_database="dev_edge_bronze",
        sf_schema="storedge_fms_public",
        sf_table="EVENTS",
        mappings=column_rule_mappings,
        has_fivetran_active=True,
        generated_by="AI",
        model_used="gpt-4o",
    )
    print(result.yaml_path)  # Path to saved .yaml file
    print(result.summary())  # Human-readable summary
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, List, Optional

from ai_transformation.column_mapping import ColumnRuleMapping
from generated_queries.sql_query_generator import SQLQueryGenerator, ValidationQuerySet
from generated_queries.yaml_config_writer import YAMLConfigWriter

if TYPE_CHECKING:
    from core.validation_plan import CanonicalValidationPlan

# ---------------------------------------------------------------------------
# Result container
# ---------------------------------------------------------------------------

@dataclass
class GenerationResult:
    """
    Result returned by QueryOutputManager.generate().

    Attributes:
        table_name         : Source table name
        yaml_path          : Absolute path to the generated data validation .yaml file
        query_set          : Full ValidationQuerySet (all SQL strings, not written to disk)
        active_columns     : Number of columns included in validation
        skipped_columns    : Column names excluded (complex types / no match)
        generated_by       : 'AI' or 'static'
        model_used         : AI model name (e.g. 'gpt-4o', 'N/A' for static)
        has_fivetran_active: Whether Snowflake _FIVETRAN_ACTIVE filter was applied
    """
    table_name: str
    yaml_path: Path
    query_set: ValidationQuerySet
    active_columns: int = 0
    skipped_columns: List[str] = field(default_factory=list)
    generated_by: str = "ai"
    model_used: str = "N/A"
    has_fivetran_active: bool = False
    dynamic_suite_yaml_path: Optional[Path] = None
    count_yaml_path: Optional[Path] = None
    plan_path: Optional[Path] = None
    coverage_headline: str = ""

    def summary(self) -> str:
        """Return a human-readable generation summary."""
        sep = "=" * 65
        skip_detail = (
            f" ({', '.join(self.skipped_columns)})"
            if self.skipped_columns
            else ""
        )
        fivetran_str = (
            "YES (WHERE _FIVETRAN_ACTIVE = TRUE)"
            if self.has_fivetran_active
            else "NO"
        )
        count_line = f"  📋 Count YAML : {self.count_yaml_path}\n" if self.count_yaml_path else ""
        dyn_line   = f"  📋 Dynamic YAML: {self.dynamic_suite_yaml_path}\n" if self.dynamic_suite_yaml_path else ""
        plan_line  = f"  📌 Plan (contract): {self.plan_path}\n" if self.plan_path else ""
        cov_line   = f"  Coverage       : {self.coverage_headline}\n" if self.coverage_headline else ""
        return (
            f"\n{sep}\n"
            f"  ✅ QUERY GENERATION COMPLETE\n"
            f"{sep}\n"
            f"  Table          : {self.table_name}\n"
            f"  Generated by   : {self.generated_by.upper()}\n"
            f"  AI Model       : {self.model_used}\n"
            f"  Active columns : {self.active_columns}\n"
            f"  Skipped columns: {len(self.skipped_columns)}{skip_detail}\n"
            f"  Fivetran filter: {fivetran_str}\n"
            f"{cov_line}"
            f"\n"
            f"{plan_line}"
            f"  📋 YAML : {self.yaml_path}\n"
            f"{count_line}"
            f"{dyn_line}"
            f"{sep}"
        )


# ---------------------------------------------------------------------------
# Query Output Manager
# ---------------------------------------------------------------------------

class QueryOutputManager:
    """
    Orchestrates SQL generation + YAML file output for a single table pair.

    Produces YAML files only (no SQL files written to disk):
      config/bronze/data_validation/<table>.yaml
      config/bronze/count_validation/bronze.yaml
    """

    def __init__(self):
        self._sql_gen     = SQLQueryGenerator()
        self._yaml_writer = YAMLConfigWriter()

    def generate(
        self,
        table_name: str,
        pg_schema: str,
        pg_table: str,
        sf_database: str,
        sf_schema: str,
        sf_table: str,
        mappings: List[ColumnRuleMapping],
        has_fivetran_active: bool = False,
        generated_by: str = "static",
        model_used: str = "N/A",
        source_db_type: str = "postgresql",
        output_dir: Optional[Path] = None,
    ) -> GenerationResult:
        """
        Generate all validation output for one table pair.

        Args:
            table_name         : Display name for the table (used in file names)
            pg_schema          : PostgreSQL schema (e.g. 'public')
            pg_table           : PostgreSQL table name
            sf_database        : Snowflake database name
            sf_schema          : Snowflake schema name
            sf_table           : Snowflake table name (UPPER recommended)
            mappings           : Column rule mappings from ai_transformation
            has_fivetran_active: Add WHERE _FIVETRAN_ACTIVE = TRUE on Snowflake side
            generated_by       : 'AI' or 'static'
            model_used         : AI model name used (e.g. 'gpt-4o')
            source_db_type     : Source database type (default: 'postgresql')

        Returns:
            GenerationResult with yaml_path, count_yaml_path, and summary stats.
        """
        active  = [m for m in mappings if not m.skip_validation]
        skipped = [m.source_column for m in mappings if m.skip_validation]

        print(f"\n  [QueryOutputManager] Generating output for '{table_name}'...")
        print(f"    Active columns  : {len(active)}")
        print(f"    Skipped columns : {len(skipped)}")
        print(f"    Fivetran filter : {has_fivetran_active}")
        print(f"    Generated by    : {generated_by} (model: {model_used})")

        # ── Step 1: Generate all SQL queries (in memory only) ─────────────────
        query_set = self._sql_gen.generate(
            pg_schema=pg_schema,
            pg_table=pg_table,
            sf_database=sf_database,
            sf_schema=sf_schema,
            sf_table=sf_table,
            mappings=active,
            has_fivetran_active=has_fivetran_active,
            generated_by=generated_by,
            model_used=model_used,
            source_db_type=source_db_type,
        )

        # ── Step 2: Save YAML config file → config/<layer>/data_validation/ ──
        yaml_path = self._yaml_writer.write(
            query_set=query_set,
            source_db_type=source_db_type,
            pg_schema=pg_schema,
            pg_table=pg_table,
            sf_database=sf_database,
            sf_schema=sf_schema,
            sf_table=sf_table,
            mappings=active,
            has_fivetran_active=has_fivetran_active,
            output_dir=output_dir,
        )

        # ── Step 3: Save count-only YAML → config/<layer>/count_validation/ ──
        count_yaml_path = self._yaml_writer.write_count_yaml(
            query_set=query_set,
            source_db_type=source_db_type,
            pg_schema=pg_schema,
            pg_table=pg_table,
            sf_database=sf_database,
            sf_schema=sf_schema,
            sf_table=sf_table,
            has_fivetran_active=has_fivetran_active,
            output_dir=output_dir,
        )

        result = GenerationResult(
            table_name=table_name,
            yaml_path=yaml_path,
            query_set=query_set,
            active_columns=len(active),
            skipped_columns=skipped,
            generated_by=generated_by,
            model_used=model_used,
            has_fivetran_active=has_fivetran_active,
            count_yaml_path=count_yaml_path,
        )

        print(result.summary())
        return result

    # -----------------------------------------------------------------------
    # Private helpers
    # -----------------------------------------------------------------------

    def generate_from_plan(self, plan: "CanonicalValidationPlan", output_dir: Optional[Path] = None, layer: str = "bronze") -> GenerationResult:
        """
        Generate all validation output from a CanonicalValidationPlan.

        Order matters: the plan is persisted FIRST, then rendered. The plan is
        the contract; if rendering fails we still have a durable record of what
        this run intended to validate and what it excluded.

        Args:
            plan: Fully validated CanonicalValidationPlan

        Returns:
            GenerationResult with yaml_path, count_yaml_path, plan_path, and stats.
        """
        from core.exclusion_report import ExclusionReport
        from core.plan_store import PlanStore

        active  = plan.active_mappings
        skipped = plan.skipped_mappings

        print(f"\n  [QueryOutputManager] Generating output from plan for '{plan.source_table}'...")
        print(f"    Fivetran filter : {plan.has_fivetran_active}")
        print(f"    Generated by    : {plan.generated_by} (model: {plan.model_used})")
        print(f"    Exact matches   : {len(plan.exact_matches)}")
        print(f"    Fuzzy matches   : {len(plan.fuzzy_matches)}")
        print(f"    AI-resolved     : {len(plan.ai_resolved_matches)}")

        # ── Contract first ───────────────────────────────────────────────────
        plan_path = PlanStore().save(plan, layer=layer)
        print(f"    Plan (contract) : {plan_path}")

        # ── Loud coverage accounting ─────────────────────────────────────────
        coverage = ExclusionReport.from_plan(plan)
        print()
        print(coverage.render(indent="    "))
        print()

        # ── Render targets, both from the same plan ──────────────────────────
        if layer == "silver":
            from silver.silver_sql_emitter import emit_query_set
            query_set = emit_query_set(plan)
        else:
            query_set = self._sql_gen.generate_from_plan(plan)
        yaml_path       = self._yaml_writer.write_from_plan(plan, query_set, output_dir=output_dir, layer=layer)
        count_yaml_path = self._yaml_writer.write_count_yaml_from_plan(plan, query_set, output_dir=output_dir)

        skipped_names = [m.source_column for m in skipped]
        result = GenerationResult(
            table_name=plan.source_table,
            yaml_path=yaml_path,
            query_set=query_set,
            active_columns=len(active),
            skipped_columns=skipped_names,
            generated_by=plan.generated_by,
            model_used=plan.model_used,
            has_fivetran_active=plan.has_fivetran_active,
            count_yaml_path=count_yaml_path,
            plan_path=plan_path,
            coverage_headline=coverage.headline(),
        )
        print(result.summary())
        return result
